### ISSUE TITLE
`spawn': No such file or directory - jmeter (Errno::ENOENT)

### ISSUE THREAD

**Issue by reach2jeyan** [flood-io/ruby-jmeter#129]
Not sure where am I going wrong, but a simple example test would give me this error

Example code
```
def performance
  test do
    threads count: 10 do
      visit name: 'Google Search', url: 'http://google.com'
    end
  end.run
end

performance
```
Error I get:

`/Users/admin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open3.rb:199:in `spawn': No such file or directory - jmeter (Errno::ENOENT)`

**Comment by mrtibs2000** [comment]
I was getting this error before I realized jmeter (like the actual Apache program) was not installed.

**Comment by reach2jeyan** [comment]
@mrtibs2000 thanks for updating! I haven't installed jmeter yet, but would be glad to try it. Will keep you posted.

**Comment by rakesh87** [comment]
do we have some solution around it? I am too getting this error while running the test.

```
/Users/rakesh/.rvm/gems/ruby-2.4.2/gems/ruby-jmeter-3.1.08/lib/ruby-jmeter/extend/threads/thread_group.rb:5: warning: constant ::Fixnum is deprecated
W, [2018-06-19T15:05:04.820984 #30908]  WARN -- : Test executing locally ...
/Users/rakesh/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/open3.rb:199:in `spawn': No such file or directory - jmeter (Errno::ENOENT)
	from /Users/rakesh/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/open3.rb:199:in `popen_run'
	from /Users/rakesh/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/open3.rb:190:in `popen2e'
	from /Users/rakesh/.rvm/gems/ruby-2.4.2/gems/ruby-jmeter-3.1.08/lib/ruby-jmeter/dsl.rb:43:in `run'

```

**Comment by rakesh87** [comment]
Thank you so much @reach2jeyan I was using JMeter as a manual command, Later I installed the JMeter using `brew` It's able to run JMeter the local test
