### ISSUE TITLE
Fails to generate tests with unicode URLs

### ISSUE THREAD

**Issue by charlieda** [flood-io/ruby-jmeter#52]
Performing a test of the form
```get url: "http://example.com?unicode=åß∂˙∆¬¬"```
returns the following error:
```
/home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruby-jmeter-2.13.3/lib/ruby-jmeter/helpers/parser.rb:14:in `split': invalid byte sequence in US-ASCII (ArgumentError)
	from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruby-jmeter-2.13.3/lib/ruby-jmeter/helpers/parser.rb:14:in `parse_http_request'
	from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruby-jmeter-2.13.3/lib/ruby-jmeter/dsl.rb:108:in `get'
```
This could be due to the fact that ```URI::decode``` (called in ```Parser::parse_url```) returns a string without specific encoding information, thereby defaulting to US-ASCII, which ```split``` (Called in ```parse_http_request``` then complains about. A possible solution would be to switch to ```CGI::unescape``` which allows the specification of encoding information.

**Comment by 90kts** [comment]
Happy for you to PR this ..
